version: '3'

services:
  back1:
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - 5300:5300
    restart: unless-stopped

  back2:
    build:
      dockerfile: server/Dockerfile
      context: .
    ports:
      - 5301:5300
    restart: unless-stopped

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
    - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo

  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - 1443:1443
    depends_on:
      - back1
